---
sudo: false
language: java
matrix:
  include:
    - jdk: openjdk7
      dist: trusty
    - jdk: openjdk8
    - jdk: openjdk11
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk13
    - jdk: openjdk-ea
    - jdk: oraclejdk8
      dist: trusty
    - jdk: oraclejdk11
    - jdk: oraclejdk12
    - jdk: oraclejdk13
    - jdk: oraclejdk-ea
  allow_failures:
    - jdk: openjdk-ea
    - jdk: oraclejdk-ea
install:
  - mvn install -DskipTests=true -Dgpg.skip=true
